FROM mysql
LABEL MAINTAINER="Camille Terol <camille@cdm.io> (https://www.cdm.io)"

CMD ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]